version: "3.7"
services:
  db:
    image: mysql
    container_name: avb-whatsapp-bot-mysql
    command: --default-authentication-plugin=mysql_native_password
    envirionment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pass}
      MYSQL_USER: ${MYSQL_USER:-user}
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always
  whatsapp:
    image: node:16
    build: .
    command: yarn nonstop
    envirionment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pass}
      MYSQL_USER: ${MYSQL_USER:-user}
      WHATSAPP_PORT: ${WHATSAPP_PORT:-3000}
      WHATSAPP_USER_1: ${WHATSAPP_USER_1:-u1}
      WHATSAPP_USER_1_PW: ${WHATSAPP_USER_1_PW:-u1p}
      WHATSAPP_USER_2: ${WHATSAPP_USER_2:-u2}
      WHATSAPP_USER_2_PW: ${WHATSAPP_USER_2_PW:-u2p}
    ports:
      - "${WHATSAPP_PORT}:${WHATSAPP_PORT}"
    volumes:
      - ./whatsapp:/usr/app
    depends_on:
      - db
