
##########################################################################################################################

version: "3"

services:

##########################################################################################################################

  whatsapp:
    image: melon-yellow/node-17-avb-whatsapp
    container_name: avb-whatsapp
    build: ./whatsapp
    command: bash -c "./setup.sh"
    env_file: .env
    volumes:
      - ./whatsapp/:/usr/app/
      - /usr/app/build/
    ports:
      - "${WHATSAPP_PORT}:${WHATSAPP_PORT}"
    depends_on:
      - db
    restart: always

##########################################################################################################################
