
version: "3"

services:

  db:
    image: mysql:8
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    env_file: db.env
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    restart: always

  whatsapp:
    image: node:16
    container_name: whatsapp
    build: ./whatsapp
    command: bash -c "yarn build && yarn start"
    env_file:
      - db.env
      - .env
    ports:
      - "${WHATSAPP_PORT}:${WHATSAPP_PORT}"
    depends_on:
      - db
