version: "3.7"
services:
  db:
    image: mysql
    container_name: avb-whatsapp-bot-mysql
    command: --default-authentication-plugin=mysql_native_password
    envirionment:
      MYSQL_ROOT_PASSWORD: oqnwe38434m2o0f
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always
  bot:
    image: node:16
    build: .
    command: yarn build && yarn nonstop
    ports:
      - "1516:3000"
    volumes:
      - ./bot:/usr/app
    depends_on:
      - db
