
version: "3"

services:

  db:
    image: mysql:8
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - /var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always

  whatsapp:
    image: node:16
    container_name: whatsapp
    build: ./whatsapp
    command: bash -c "yarn && yarn build && yarn nonstop"
    env_file: .env
    volumes:
      - /usr/app/
      - ./whatsapp/src:/usr/app/src/
      - ./whatsapp/config:/usr/app/config/
      - ./whatsapp/package.json:/usr/app/package.json
      - ./whatsapp/tsconfig.json:/usr/app/tsconfig.json
    ports:
      - "${WHATSAPP_PORT}:${WHATSAPP_PORT}"
    depends_on:
      - db
    restart: always
