
##########################################################################################################################

version: "3"

services:

##########################################################################################################################

  db:
    image: mysql:8
    container_name: avb-whatsapp-db
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - ./db/data/:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    restart: always

##########################################################################################################################

  whatsapp:
    image: node:17
    container_name: avb-whatsapp
    build: ./whatsapp
    command: bash -c "yarn && yarn build && yarn nonstop"
    env_file: .env
    volumes:
      - ./whatsapp/:/usr/app/
      - /usr/app/build/
    ports:
      - "${WHATSAPP_PORT}:${WHATSAPP_PORT}"
    depends_on:
      - db
    restart: always

##########################################################################################################################
